<?php
/******************************************
US English
Admin Course Language
******************************************/

$lang['categories']					= 'Courses';
$lang['error_must_select']			= 'You must select a course to organize';
$lang['error_not_found']			= 'The requested course could not be found.';
$lang['organize_course']			= 'Organize "%s" Course';
$lang['organize']					= 'Organize';
$lang['course_id']				= 'ID';
$lang['course_form']				= 'Course Form';
$lang['name']						= 'Name';
$lang['slug']						= 'Slug';
$lang['description']				= 'Description';
$lang['excerpt']					= 'Excerpt';
$lang['sequence']					= 'Sequence';
$lang['image']						= 'Image';
$lang['seo_title']					= 'SEO Title';
$lang['meta']						= 'Meta Data';
$lang['message_course_saved']		= 'The course has been saved!';
$lang['error_file_upload']			= '<p>You did not select a file to upload.</p>'; //important. This must match the same error as generated by the file upload script of your language.
$lang['message_delete_course']	= 'The course has been deleted.';
$lang['current_file']				= 'Current File';
$lang['confirm_delete_course']	= 'Are you sure you want to delete this course?';
$lang['add_new_course']			= 'Add New Course';
$lang['no_categories']				= 'There are currently no categories';
$lang['attributes']					= 'Attributes';
$lang['seo']						= 'SEO';
$lang['parent']						= 'Parent';
$lang['meta_data_description']		= 'ex. &lt;meta name="description" content="We sell products that help you" /&gt;';
$lang['drag_and_drop']				= 'Drag and drop the products in the order you would like them to appear.';
$lang['sku']						= 'SKU';
$lang['price']						= 'Price';
$lang['sale']						= 'Sale';
$lang['max_file_size']				= 'Max File Size';